---
title: "Behavioral results"
author: "Alice M. Xue (alicexue@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
    self_contained: false
  pdf_document: 
    toc: yes
  word_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE, fig.showtext=T}
library(Hmisc)
library(ggplot2)
library(knitr)
library(kableExtra)
library(data.table)
library(psycho)
library(tidyjson)
library(lme4)
library(sjPlot)
library(afex)
library(wesanderson)
library(showtext)
library(plyr)
library(tidyverse)
library(extrafont)
library(stats)
library(patchwork)
library(broom.mixed)
library(pracma)
library(afex)
library(emmeans)

font_add(family = "Avenir Next",
         regular = "../utils/AvenirNext-Regular.ttf",
         bold = "../utils/AvenirNext-DemiBold.ttf",
         italic = "../utils/AvenirNext-Italic.ttf")
showtext.auto()

set_theme(
  base=theme_classic(base_size = 12,
                     base_family="Avenir Next",
                     base_line_size = 12/30,
                     base_rect_size = 12/30)
)

options(dplyr.summarise.inform = FALSE)

knitr::opts_chunk$set(echo = TRUE, 
                      warning=FALSE, 
                      message = FALSE, 
                      fig.showtext=TRUE)

#knitr::opts_chunk$set(dev = 'pdf') # set output device to pdf

grbl_palette <- c("#008080", "#9fdfbf")

greek.beta <- "\u03B2"

source("../utils/summary_se_utils.R")
```

```{r, echo=F}

data_ret <- fread("../../data/behavior/MPE_asso_retrieval_behavior.csv") %>% 
  mutate(key = match_response.keys,
         rt = match_response.rt * 1000)

data_recog <- fread("../../data/behavior/MPE_mismatch_recog_behavior.csv") %>% 
  mutate(rt = recognition_response.rt * 1000)

```

```{r, echo=F}
data_memory <- merge(data_ret %>%
                       dplyr::filter(is_match == F) %>% 
                       select(subjectId, 
                              expId,
                              room_setup,
                              is_match, 
                              probe, 
                              correct_associate, 
                              probe_category, 
                              rt, 
                              match_response.keys,
                              correct.ret, 
                              association_strength,
                              block_n), 
                     data_recog, 
                     by.x=c("subjectId","probe"), 
                     by.y=c("subjectId","stimulus"), 
                     suffixes = c(".ret",".recog"), all=T)

data_memory <- data_memory %>% 
  mutate(association_strength = ifelse(is_old & is.na(association_strength), 
                                       "Familiar item",
                                       association_strength)) %>% 
  mutate(association_strength = replace_na(association_strength, "Novel item")) %>% 
  mutate(old_new = ifelse(is_old, "Old", "New"))
```

### Associative retrieval

Removing trials where RT \< 250ms or RT \> 1000ms

```{r assoc_retrieval_behavior, echo=F}
data_ret <- data_ret %>% 
  dplyr::filter(!is.na(association_strength))

data_ret <- data_ret %>%
  dplyr::filter(!is.na(rt)) %>%
  dplyr::filter(rt <= 1000) %>% # remove trials where RT > 1000ms
  dplyr::filter(rt >= 250) # remove trials where RT < 250ms
```

```{r assoc_retrieval_dprime, echo=F}
kable(data_ret %>%
        mutate(is_hit = is_match & (key==1)) %>%
        mutate(is_false_alarm = !is_match & (key==1)) %>%
        mutate(is_miss = is_match & (key==2)) %>%
        mutate(is_correct_rejection = !is_match & (key==2)) %>%
        mutate(no_response = is.na(rt)) %>%
        group_by(subjectId, association_strength) %>%
        summarize(n_hit = sum(is_hit, na.rm=T) / (sum(is_hit, na.rm=T) + sum(is_miss, na.rm=T)), 
                  n_fa = sum(is_false_alarm, na.rm=T) / (sum(is_false_alarm, na.rm=T) + sum(is_correct_rejection, na.rm=T)),
                  n_miss = sum(is_miss, na.rm=T) / (sum(is_hit, na.rm=T) + sum(is_miss, na.rm=T)), 
                  n_cr = sum(is_correct_rejection, na.rm=T) / (sum(is_false_alarm, na.rm=T) + sum(is_correct_rejection, na.rm=T)), 
                  n_nr = mean(no_response, na.rm=T)) %>%
        ungroup() %>% 
        group_by(association_strength) %>%
        summarize(hit = sprintf("%.1f", mean(n_hit, na.rm=T)*100), 
                  sd_hit = sprintf("(%.1f)", sd(n_hit, na.rm=T)*100),
                  fa = sprintf("%.1f", mean(n_fa, na.rm=T)*100), 
                  sd_fa = sprintf("(%.1f)", sd(n_fa, na.rm=T)*100),
                  miss = sprintf("%.1f", mean(n_miss, na.rm=T)*100), 
                  sd_miss = sprintf("(%.1f)", sd(n_miss, na.rm=T)*100),
                  cr = sprintf("%.1f", mean(n_cr, na.rm=T)*100),
                  sd_cr = sprintf("(%.1f)", sd(n_cr, na.rm=T)*100)) %>%
        ungroup() %>% 
        select(association_strength, hit, sd_hit, fa, sd_fa, miss, sd_miss, cr, sd_cr),
      col.names = c("association_strength", "% hit", "(sd)", "% fa", 
                    "(sd)", "% miss", "(sd)", "% cr", "(sd)")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

ret_dprime <- data_ret %>%
  dplyr::filter(!is.na(rt)) %>%
  mutate(is_hit = is_match & correct.ret) %>%
  mutate(is_false_alarm = !is_match & (key==1)) %>%
  mutate(is_miss = is_match & !correct.ret) %>%
  mutate(is_correct_rejection = !is_match & (key==2)) %>%
  group_by(subjectId, association_strength, expId) %>%
  summarize(n_hit = sum(is_hit), 
            n_fa = sum(is_false_alarm), 
            n_miss = sum(is_miss),
            n_cr = sum(is_correct_rejection)) %>%
  ungroup() %>% 
  rowwise() %>%
  mutate(dprime_results = list(psycho::dprime(n_hit, n_fa, n_miss, n_cr, adjusted=T))) %>%
  mutate(dprime = dprime_results$dprime, 
         dprime_beta = dprime_results$beta, 
         dprime_c = dprime_results$c) %>%
  select(-dprime_results) %>% 
  ungroup() %>% 
  group_by(association_strength, expId) %>% 
  mutate(median_strength_dprime = median(dprime)) %>% 
  ungroup() %>% 
  mutate(above_median_dprime = dprime >= median_strength_dprime)
```

### Recognition

```{r recognition_dprime, echo=F}
ret_data_conditions <- data_ret %>% 
  select(subjectId, 
         probe, 
         association_strength, 
         trial_condition,
         correct.ret) %>% 
  mutate(img = probe) %>% 
  dplyr::filter(trial_condition == "Mismatch") %>% 
  select(-probe, -trial_condition) 

kable(data_recog %>%
        mutate(img = stimulus) %>% 
        left_join(ret_data_conditions, by = c("subjectId", "img")) %>% 
        mutate(association_strength = ifelse(is_old & is.na(association_strength),
                                             "Familiar item",
                                             association_strength)) %>% 
        dplyr::filter(correct.ret == T | !is_old | association_strength == "Familiar item") %>%
        mutate(association_strength = ifelse(is.na(association_strength), "Novel", association_strength)) %>% 
        mutate(is_hit = is_old & (old_new_rsp=="old")) %>%
        mutate(is_false_alarm = !is_old & (old_new_rsp=="old")) %>%
        mutate(is_miss = is_old & (old_new_rsp=="new")) %>%
        mutate(is_correct_rejection = !is_old & (old_new_rsp=="new")) %>%
        mutate(no_response = is.na(rt)) %>%
        group_by(subjectId, association_strength) %>%
        summarize(n_hit = sum(is_hit, na.rm=T) / 
                    (sum(is_hit, na.rm=T) + sum(is_miss, na.rm=T)) * 100, 
                  n_fa = sum(is_false_alarm, na.rm=T) / 
                    (sum(is_false_alarm, na.rm=T) + 
                       sum(is_correct_rejection, na.rm=T)) *100, 
                  n_miss = sum(is_miss, na.rm=T) / 
                    (sum(is_hit, na.rm=T) + sum(is_miss, na.rm=T)) * 100, 
                  n_cr = sum(is_correct_rejection, na.rm=T) / 
                    (sum(is_false_alarm, na.rm=T) + 
                       sum(is_correct_rejection, na.rm=T)) * 100) %>%
        ungroup() %>% 
        group_by(association_strength) %>%
        summarize(hit = sprintf("%.1f", mean(n_hit, na.rm=T)), 
                  sd_hit = sprintf("(%.1f)", sd(n_hit, na.rm=T)),
                  fa = sprintf("%.1f", mean(n_fa, na.rm=T)), 
                  sd_fa = sprintf("(%.1f)", sd(n_fa, na.rm=T)),
                  miss = sprintf("%.1f", mean(n_miss, na.rm=T)), 
                  sd_miss = sprintf("(%.1f)", sd(n_miss, na.rm=T)),
                  cr = sprintf("%.1f", mean(n_cr, na.rm=T)),
                  sd_cr = sprintf("(%.1f)", sd(n_cr, na.rm=T))) %>%
        ungroup() %>% 
        mutate(across(everything(), ~replace(., . == "NaN", " "))) %>% 
        mutate(across(everything(), ~replace(., . == "NA", " "))) %>% 
        mutate(across(everything(), ~replace(., . == "(NA)", " "))) %>% 
        arrange(match(association_strength, c("Strong (4x)", "Weak (1x)", "Familiar item", "Novel"))) %>% 
        select(association_strength, hit, sd_hit, fa, sd_fa, 
               miss, sd_miss, cr, sd_cr),
      col.names = c("association_strength", "% hit", "(sd)", "% fa", "(sd)", 
                    "% miss", "(sd)", "% cr", "(sd)")) %>%
  kable_styling(bootstrap_options = "striped", 
                full_width = F, 
                position = "left")
```

```{r recognition_dprime_cr_mismatch, echo=F}
recog_dprime_strong <- data_recog %>%
  left_join(ret_data_conditions, by = c("subjectId", "img")) %>% 
  dplyr::filter(association_strength == "Strong (4x)" | !is_old,
                correct.ret == T | !is_old) %>% 
  dplyr::filter(!is.na(rt)) %>%
  mutate(is_hit = is_old & (old_new_rsp=="old")) %>%
  mutate(is_false_alarm = !is_old & (old_new_rsp=="old")) %>%
  mutate(is_miss = is_old & (old_new_rsp=="new")) %>%
  mutate(is_correct_rejection = !is_old & (old_new_rsp=="new")) %>%
  group_by(subjectId, expId) %>%
  summarize(n_hit = sum(is_hit), 
            n_fa = sum(is_false_alarm), 
            n_miss = sum(is_miss),
            n_cr = sum(is_correct_rejection)) %>%
  ungroup() %>% 
  rowwise() %>%
  mutate(dprime_results = list(psycho::dprime(n_hit, n_fa, n_miss, n_cr, adjusted=T))) %>%
  mutate(dprime = dprime_results$dprime, 
         dprime_beta = dprime_results$beta, 
         dprime_c = dprime_results$c) %>%
  ungroup() %>% 
  select(-dprime_results) %>% 
  mutate(association_strength = "Strong (4x)")

recog_dprime_weak <- data_recog %>%
  left_join(ret_data_conditions, by = c("subjectId", "img")) %>% 
  dplyr::filter(association_strength == "Weak (1x)" | !is_old,
                correct.ret == T | !is_old) %>% 
  dplyr::filter(!is.na(rt)) %>%
  mutate(is_hit = is_old & (old_new_rsp=="old")) %>%
  mutate(is_false_alarm = !is_old & (old_new_rsp=="old")) %>%
  mutate(is_miss = is_old & (old_new_rsp=="new")) %>%
  mutate(is_correct_rejection = !is_old & (old_new_rsp=="new")) %>%
  group_by(subjectId, expId) %>%
  summarize(n_hit = sum(is_hit), 
            n_fa = sum(is_false_alarm), 
            n_miss = sum(is_miss),
            n_cr = sum(is_correct_rejection)) %>%
  ungroup() %>% 
  rowwise() %>%
  mutate(dprime_results = list(psycho::dprime(n_hit, n_fa, n_miss, n_cr, adjusted=T))) %>%
  mutate(dprime = dprime_results$dprime, 
         dprime_beta = dprime_results$beta, 
         dprime_c = dprime_results$c) %>%
  ungroup() %>% 
  select(-dprime_results) %>% 
  mutate(association_strength = "Weak (1x)")

recog_dprime_fam <- data_recog %>%
  left_join(ret_data_conditions, by = c("subjectId", "img")) %>% 
  mutate(association_strength = ifelse(is_old & is.na(association_strength),
                                       "Familiar item",
                                       association_strength)) %>% 
  dplyr::filter(association_strength == "Familiar item" | !is_old) %>% 
  dplyr::filter(!is.na(rt)) %>%
  mutate(is_hit = is_old & (old_new_rsp=="old")) %>%
  mutate(is_false_alarm = !is_old & (old_new_rsp=="old")) %>%
  mutate(is_miss = is_old & (old_new_rsp=="new")) %>%
  mutate(is_correct_rejection = !is_old & (old_new_rsp=="new")) %>%
  group_by(subjectId, expId) %>%
  summarize(n_hit = sum(is_hit), 
            n_fa = sum(is_false_alarm), 
            n_miss = sum(is_miss),
            n_cr = sum(is_correct_rejection)) %>%
  ungroup() %>% 
  rowwise() %>%
  mutate(dprime_results = list(psycho::dprime(n_hit, n_fa, n_miss, n_cr, adjusted=T))) %>%
  mutate(dprime = dprime_results$dprime, 
         dprime_beta = dprime_results$beta, 
         dprime_c = dprime_results$c) %>%
  ungroup() %>% 
  select(-dprime_results) %>% 
  mutate(association_strength = "Familiar item")

recog_dprime <- rbind(recog_dprime_strong, recog_dprime_weak, recog_dprime_fam)

```

### Main figures

```{r grbl_plots_ret, echo=F, fig.width=7.5, fig.height=3.5}
### ASSOCIATIVE RETRIEVAL; D-PRIME

ret.dprime.plt <- ret_dprime %>%
  ggplot(aes(x=association_strength, 
             y=dprime,
             fill=association_strength)) +
  geom_line(aes(group = subjectId),
            color = "lightgray",
            alpha = 1,
            size = 0.4) + 
  geom_jitter(height = 0,
              width = 0,
              size = 1.8,
              alpha = 1,
              shape = 21,
              color = "black") + 
  stat_summary(fun.data="mean_cl_boot",
               geom="pointrange", 
               size = 0.6,
               fill = "white",
               color = "black",
               shape = 23) +
  labs(x = "", 
       y = "d'",
       title = "Associative memory") + 
  scale_color_manual(values = grbl_palette) + 
  scale_fill_manual(values = grbl_palette) + 
  guides(color="none", fill="none") +
  theme(axis.title.y = element_text(face = "italic"))

### ASSOCIATIVE RETRIEVAL; RT

level_order = c("Match", "Mismatch", "Miss\n(match)", "False alarm\n(mismatch)")

data_ret.rt.data <- data_ret %>%
  mutate(hit = is_match & (key==1)) %>%
  mutate(false_alarm = !is_match & (key==1)) %>%
  mutate(miss = is_match & (key==2)) %>%
  mutate(correct_rejection = !is_match & (key==2)) %>%
  mutate(trial_outcome = case_when(hit ~ "Match",
                                   false_alarm ~ "False alarm\n(mismatch)",
                                   miss ~ "Miss\n(match)",
                                   correct_rejection ~ "Mismatch")) %>%
  dplyr::filter(!is.na(trial_outcome))

ret.rt.plt <- data_ret.rt.data %>% 
  group_by(subjectId, trial_outcome, association_strength) %>%
  summarize(median_rt = median(rt)) %>%
  ungroup() %>% 
  summarySEwithin(.,
                  measurevar="median_rt",
                  withinvars=c("association_strength",
                               "trial_outcome"),
                  idvar="subjectId") %>%
  ggplot(aes(x = factor(trial_outcome, level=level_order), 
             y = median_rt, 
             fill = association_strength)) + 
  stat_summary(fun = "mean", 
               geom = "bar", 
               color = "black", 
               position=position_dodge()) +
  geom_errorbar(aes(ymin=median_rt-se, ymax=median_rt+se),
                position=position_dodge(.9), 
                width=.2) +
  labs(title = "", 
       x = "", 
       y = "RT (ms)", 
       fill = "") + 
  scale_fill_manual(values = grbl_palette) #+ 
#guides(fill="none")


ret.dprime.plt + ret.rt.plt +
  plot_layout(widths=c(1, 1.2)) &
  theme(
    text = element_text(size = 10)
  )

ret_dprime %>% 
  group_by(association_strength) %>% 
  summarize(mean.dprime = mean(dprime),
            sd.dprime = sd(dprime)) %>% 
  kable(digits=2) %>% 
  kable_styling()

```

```{r grbl_plots_ret_exp, echo=F, fig.width=12, fig.height=3.5}

ret.dprime.plt <- ret_dprime %>%
  mutate(expId = case_when(as.character(expId) == "imm" ~ "Experiment 1",
                           as.character(expId) == "del" ~ "Experiment 2")) %>%
  mutate(across(expId,
                factor,
                levels = c("Experiment 1", "Experiment 2"))) %>% 
  ggplot(aes(x=association_strength, 
             y=dprime,
             fill=association_strength)) +
  geom_line(aes(group = subjectId),
            color = "lightgray",
            alpha = 1,
            size = 0.4) + 
  geom_jitter(height = 0,
              width = 0,
              size = 1.8,
              alpha = 1,
              shape = 21,
              color = "black") + 
  stat_summary(fun.data="mean_cl_boot",
               geom="pointrange", 
               size = 0.6,
               fill = "white",
               color = "black",
               shape = 23) +
  labs(x = "", 
       y = "d'",
       title = "Associative memory") + 
  scale_color_manual(values = grbl_palette) + 
  scale_fill_manual(values = grbl_palette) + 
  guides(color="none", fill="none") + 
  facet_wrap(~expId) + 
  theme(axis.title.y = element_text(face = "italic"))

ret.rt.plt <- data_ret.rt.data %>% 
  mutate(expId = case_when(as.character(expId) == "imm" ~ "Experiment 1",
                           as.character(expId) == "del" ~ "Experiment 2")) %>%
  mutate(across(expId,
                factor,
                levels = c("Experiment 1", "Experiment 2"))) %>% 
  group_by(subjectId, trial_outcome, association_strength, expId) %>%
  summarize(median_rt = median(rt)) %>%
  ungroup() %>% 
  summarySEwithin(.,
                  measurevar="median_rt",
                  withinvars=c("association_strength",
                               "trial_outcome"),
                  betweenvars=c("expId"),
                  idvar="subjectId") %>%
  ggplot(aes(x = factor(trial_outcome, level=level_order), 
             y = median_rt, 
             fill = association_strength)) + 
  stat_summary(fun = "mean", 
               geom = "bar", 
               color = "black", 
               position=position_dodge()) +
  geom_errorbar(aes(ymin=median_rt-se, ymax=median_rt+se),
                position=position_dodge(.9), 
                width=.2) +
  labs(title = "", 
       x = "", 
       y = "RT (ms)", 
       fill = "") + 
  scale_fill_manual(values = grbl_palette) + 
  facet_wrap(~expId)

ret.dprime.plt + ret.rt.plt +
  plot_layout(widths=c(1, 1.2)) &
  theme(
    text = element_text(size = 10),
    strip.text.x = element_text(size=12)
  )

ret_dprime %>% 
  group_by(association_strength, expId) %>% 
  summarize(mean.dprime = mean(dprime),
            sd.dprime = sd(dprime)) %>% 
  kable(digits=2) %>% 
  kable_styling()
```


```{r grbl_plots_recog, echo=F, fig.width=12, fig.height=3.5}
### RECOGNITION; D-PRIME

recog.dprime.plt <- recog_dprime %>%
  mutate(association_strength = replace(association_strength,
                                        association_strength == "Familiar item", "Familiar\nitem")) %>% 
  mutate(association_strength = replace(association_strength,
                                        association_strength == "Strong (4x)", "Strong\nmismatch")) %>% 
  mutate(association_strength = replace(association_strength,
                                        association_strength == "Weak (1x)", "Weak\nmismatch")) %>% 
  mutate(expId = case_when(as.character(expId) == "imm" ~ "Experiment 1 (same day)",
                           as.character(expId) == "del" ~ "Experiment 2 (48 hours later)")) %>%
  mutate(across(expId,
                factor,
                levels = c("Experiment 1 (same day)", 
                           "Experiment 2 (48 hours later)"))) %>% 
  ggplot(aes(x = association_strength, 
             y = dprime, 
             fill = association_strength,
             color = association_strength)) +
  geom_line(aes(group = subjectId),
            color = "lightgray",
            size = 0.4) + 
  geom_jitter(height = 0,
              width = 0,
              size = 1.8,
              alpha = 1,
              shape = 21,
              color = "black") + 
  stat_summary(fun.data="mean_cl_boot", 
               geom="pointrange", 
               color="black",
               size = 0.6,
               fill = "white",
               color = "black",
               shape = 23) +
  labs(x = "", 
       y = "d'",
       title = "Mismatch recognition") + 
  scale_fill_manual(values = c("darkgray", grbl_palette)) +  
  guides(fill="none") +
  facet_wrap(~expId) + 
  theme(axis.title.y = element_text(face = "italic"))

### RECOGNITION; RT

level_order = c("Hit", "Miss", "CR", "FA")

data_recog.rt.data <- data_recog %>%
  left_join(ret_data_conditions, by = c("subjectId", "img")) %>% 
  mutate(is_hit = is_old & (old_new_rsp=="old")) %>%
  mutate(is_false_alarm = !is_old & (old_new_rsp=="old")) %>%
  mutate(is_miss = is_old & (old_new_rsp=="new")) %>%
  mutate(is_correct_rejection = !is_old & (old_new_rsp=="new")) %>%
  mutate(no_response = is.na(rt)) %>%
  mutate(trial_outcome = case_when(is_hit ~ "Hit",
                                   is_false_alarm ~ "FA",
                                   is_miss ~ "Miss",
                                   is_correct_rejection ~ "CR")) %>%
  dplyr::filter(!is.na(trial_outcome)) %>% 
  mutate(association_strength = ifelse(is_old & is.na(association_strength),
                                       "Familiar",
                                       association_strength)) %>%  
  mutate(association_strength = ifelse(is.na(association_strength),
                                       "New",
                                       association_strength)) %>%  
  dplyr::filter(correct.ret | !is_old | association_strength == "Familiar") %>% 
  mutate(across(association_strength,
                factor,
                levels = c("Strong (4x)", "Weak (1x)", "Familiar", "New"))) 


recog.rt.plt <- data_recog.rt.data %>% 
  mutate(expId = case_when(as.character(expId) == "imm" ~ "Experiment 1 (same day)",
                           as.character(expId) == "del" ~ "Experiment 2 (48 hours later)")) %>%
  mutate(across(expId,
                factor,
                levels = c("Experiment 1 (same day)", 
                           "Experiment 2 (48 hours later)"))) %>% 
  group_by(subjectId, trial_outcome, association_strength, expId) %>%
  summarize(median_rt = median(rt)) %>%
  ungroup() %>% 
  summarySEwithin(.,
                  measurevar="median_rt",
                  withinvars=c("association_strength",
                               "trial_outcome"),
                  betweenvars=c("expId"),
                  idvar="subjectId") %>%
  ggplot(aes(x = factor(trial_outcome, level_order), 
             y = median_rt, 
             fill = association_strength)) + 
  stat_summary(fun = "mean", 
               geom = "bar", 
               color = "black", 
               position=position_dodge()) +
  geom_errorbar(aes(ymin=median_rt-se, ymax=median_rt+se),
                position=position_dodge(.9), 
                width=.2) +
  labs(title = "", 
       x = "", 
       y = "RT (ms)", 
       fill = "") + 
  scale_fill_manual(values = c(grbl_palette, "darkgray", "gray89")) + 
  facet_wrap(~expId)

recog.dprime.plt + recog.rt.plt +
  plot_layout(widths=c(1.2, 1.2)) &
  theme(
    text = element_text(size = 10),
    strip.text.x = element_text(size=12) 
  )

recog_dprime %>% 
  group_by(association_strength, expId) %>% 
  summarize(mean.dprime = mean(dprime),
            sd.dprime = sd(dprime)) %>% 
  kable(digits=2) %>% 
  kable_styling()
```

### Statistics

```{r stats, echo=T}

mod <- lm(dprime ~ association_strength * expId,
          data = ret_dprime)

tidy(mod, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(term, estimate, conf.low, conf.high, p.value, std.error) %>% 
  kable(caption=paste("ret_dprime ~", formula(mod)[3]), digits=3)%>% 
  kable_styling()

tidy(anova(mod))

t.test(x = ret_dprime %>% 
         dplyr::filter(association_strength == "Strong (4x)") %>% 
         pull(dprime),  
       y = ret_dprime %>% 
         dplyr::filter(association_strength == "Weak (1x)") %>% 
         pull(dprime),
       alternative = "two.sided",
       mu = 0, paired = TRUE)

###

mod <- lm(dprime ~ association_strength * expId,
          data = recog_dprime %>% 
            mutate(across(association_strength, 
                          factor, 
                          levels=c("Strong (4x)", "Weak (1x)", "Familiar item"))))

tidy(mod, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(term, estimate, conf.low, conf.high, p.value, std.error) %>% 
  kable(caption=paste("recog_dprime ~", formula(mod)[3]), digits=3)%>% 
  kable_styling()

tidy(anova(mod))

emm <- emmeans(mod, ~ association_strength | expId, adjust="bonferroni")
emm.pairs <- pairs(emm)
tidy(emm.pairs, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(expId, contrast, estimate, conf.low, conf.high, adj.p.value, std.error) %>% 
  kable(digits=3, caption="Recog d-prime comparisons") %>% 
  kable_styling()

t.test(x = recog_dprime %>% 
         dplyr::filter(expId == "imm") %>% 
         dplyr::filter(association_strength == "Strong (4x)") %>% 
         pull(dprime),  
       y = recog_dprime %>% 
         dplyr::filter(expId == "imm") %>% 
         dplyr::filter(association_strength == "Weak (1x)") %>% 
         pull(dprime),
       alternative = "two.sided",
       mu = 0, paired = TRUE)

t.test(x = recog_dprime %>% 
         dplyr::filter(expId == "imm") %>% 
         dplyr::filter(association_strength == "Strong (4x)") %>% 
         pull(dprime),  
       y = recog_dprime %>% 
         dplyr::filter(expId == "imm") %>% 
         dplyr::filter(association_strength == "Familiar item") %>% 
         pull(dprime),
       alternative = "two.sided",
       mu = 0, paired = TRUE)

t.test(x = recog_dprime %>% 
         dplyr::filter(expId == "imm") %>% 
         dplyr::filter(association_strength == "Weak (1x)") %>% 
         pull(dprime),  
       y = recog_dprime %>% 
         dplyr::filter(expId == "imm") %>% 
         dplyr::filter(association_strength == "Familiar item") %>% 
         pull(dprime),
       alternative = "two.sided",
       mu = 0, paired = TRUE)

###

t.test(x = recog_dprime %>% 
         dplyr::filter(expId == "del") %>% 
         dplyr::filter(association_strength == "Strong (4x)") %>% 
         pull(dprime),  
       y = recog_dprime %>% 
         dplyr::filter(expId == "del") %>% 
         dplyr::filter(association_strength == "Weak (1x)") %>% 
         pull(dprime),
       alternative = "two.sided",
       mu = 0, paired = TRUE)

t.test(x = recog_dprime %>% 
         dplyr::filter(expId == "del") %>% 
         dplyr::filter(association_strength == "Strong (4x)") %>% 
         pull(dprime),  
       y = recog_dprime %>% 
         dplyr::filter(expId == "del") %>% 
         dplyr::filter(association_strength == "Familiar item") %>% 
         pull(dprime),
       alternative = "two.sided",
       mu = 0, paired = TRUE)

t.test(x = recog_dprime %>% 
         dplyr::filter(expId == "del") %>% 
         dplyr::filter(association_strength == "Weak (1x)") %>% 
         pull(dprime),  
       y = recog_dprime %>% 
         dplyr::filter(expId == "del") %>% 
         dplyr::filter(association_strength == "Familiar item") %>% 
         pull(dprime),
       alternative = "two.sided",
       mu = 0, paired = TRUE)

```


```{r ret_rt_stats, echo=F}

data_ret.rt.data %>% 
  group_by(subjectId, association_strength, correct.ret, is_match_trial) %>% 
  summarize(median_rt = median(rt)) %>% 
  group_by(association_strength, correct.ret, is_match_trial) %>% 
  summarize(mean.rt = mean(median_rt),
            sd.rt = sd(median_rt)) %>% 
  kable(digits=2) %>% 
  kable_styling()

data_ret.rt.data %>% 
  group_by(subjectId, association_strength, correct.ret, is_match_trial, expId) %>% 
  summarize(median_rt = median(rt)) %>% 
  group_by(association_strength, correct.ret, is_match_trial, expId) %>% 
  summarize(mean.rt = mean(median_rt),
            sd.rt = sd(median_rt)) %>% 
  kable(digits=2) %>% 
  kable_styling()


ret.rt.mod <- data_ret.rt.data %>% 
  mutate(rt = log(rt),
         incorrect.ret = ifelse(correct.ret,
                                0,
                                1),
         is_mismatch = ifelse(is_match_trial,
                              0,
                              1)) %>% 
  lmer(rt ~ association_strength * incorrect.ret * is_mismatch + 
         (incorrect.ret | subjectId) + 
         (1 | expId),
       data = .)

tidy(ret.rt.mod, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(term, estimate, conf.low, conf.high, p.value, std.error) %>% 
  kable(caption=paste(formula(ret.rt.mod)[3]), digits=3)%>% 
  kable_styling()

emm <- emmeans(ret.rt.mod, ~ is_mismatch | association_strength | incorrect.ret, adjust="bonferroni")
emm.pairs <- pairs(emm)
tidy(emm.pairs, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(association_strength, incorrect.ret, contrast, estimate, conf.low, conf.high, p.value, std.error) %>% 
  kable(digits=3, caption="Retrieval match/mismatch RT differences") %>% 
  kable_styling()

###

ret.rt.mod <- data_ret.rt.data %>% 
  mutate(rt = log(rt),
         incorrect.ret = ifelse(correct.ret,
                                0,
                                1),
         is_mismatch = ifelse(is_match_trial,
                              0,
                              1)) %>% 
  lmer(rt ~ association_strength * incorrect.ret * is_mismatch * expId + 
         (incorrect.ret | subjectId),
       data = .)

tidy(ret.rt.mod, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(term, estimate, conf.low, conf.high, p.value, std.error) %>% 
  kable(caption=paste(formula(ret.rt.mod)[3]), digits=3)%>% 
  kable_styling()

emm <- emmeans(ret.rt.mod, ~ is_mismatch | association_strength | incorrect.ret | expId, adjust="bonferroni")
emm.pairs <- pairs(emm)
tidy(emm.pairs, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(expId, association_strength, incorrect.ret, contrast, estimate, conf.low, conf.high, p.value, std.error) %>% 
  kable(digits=3, caption="Retrieval match/mismatch RT differences") %>% 
  kable_styling()

```


```{r recog_rt_stats, echo=F}
data_recog.rt.data %>% 
  group_by(subjectId, association_strength, correct.recog) %>% 
  summarize(median_rt = median(rt)) %>% 
  group_by(association_strength, correct.recog) %>% 
  summarize(mean.rt = mean(median_rt),
            sd.rt = sd(median_rt)) %>% 
  kable(digits=2) %>% 
  kable_styling()

recog.rt.mod <- data_recog.rt.data %>% 
  mutate(rt = log(rt),
         incorrect.recog = ifelse(correct.recog,
                                  0,
                                  1)) %>% 
  lmer(rt ~ association_strength * incorrect.recog * expId + 
         (incorrect.recog | subjectId),
       data = .)

tidy(recog.rt.mod, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  mutate(CI = paste0("[", 
                     sprintf("%.03f", conf.low), 
                     ", ", 
                     sprintf("%.03f", conf.high), 
                     "]", 
                     sep="")) %>% 
  select(term, estimate, CI, p.value, std.error, df) %>% 
  rename("Estimate" = estimate,
         "p-value" = p.value,
         "SE" = std.error,
         "DF" = df
  ) %>% 
  mutate(term = gsub("is_mismatch", "Mismatch", term),
         term = gsub("incorrect.recog", "Accuracy", term),
         term = gsub("expIddel", "Experiment", term),
         term = gsub(":", " x ", term),
         term = gsub("association_strengthWeak \\(1x\\)", "Memory strength (Weak)", term),
         term = gsub("association_strengthFamiliar", "Memory strength (Familiar)", term),
         term = gsub("association_strengthNew", "Memory strength (New)", term)) %>% 
  kable(caption=paste("Recognition RT ~", formula(recog.rt.mod)[3]), digits=3)%>% 
  kable_styling()

emm <- emmeans(recog.rt.mod, ~ association_strength | incorrect.recog | expId, adjust="bonferroni")
emm.pairs <- pairs(emm)
tidy(emm.pairs, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(expId,incorrect.recog, contrast, estimate, conf.low, conf.high, adj.p.value, std.error) %>% 
  kable(digits=3, caption="Recognition RT main effects") %>% 
  kable_styling()

emm <- emmeans(recog.rt.mod, ~ association_strength * incorrect.recog | expId, adjust="bonferroni")
con <- contrast(emm, interaction = "pairwise")
tidy(con, effects = "fixed", conf.int = T, conf.level = 0.95) %>% 
  select(expId, association_strength_pairwise, incorrect.recog_pairwise, estimate, conf.low, conf.high, p.value, std.error) %>% 
  kable(digits=3, caption="Recognition RT interactions") %>% 
  kable_styling()

```


